alias diff="colordiff"
alias feh="feh --scale-down"
alias grep="grep --color=always"
alias hex="xxd -p"
alias less="less -R"
alias ls="ls -a --color=always"
alias reboot="systemctl reboot"
alias shutdown="systemctl poweroff"
alias suspend="systemctl suspend"
alias vi="vim"
