alias diff="colordiff"
alias feh="feh --scale-down"
alias hex="xxd -p"
alias ls="ls -a --color=always"
alias pacman-log="cat /var/log/pacman.log"
alias reboot="systemctl reboot"
alias shutdown="systemctl poweroff"
alias suspend="systemctl suspend"
alias vi="vim"
